Docio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('randwordly.urls')),
    path('', include('registration.urls')),
]

randwordly/urls.py
from django.urls import path

from . import views

app_name = 'randwordly'
urlpatterns = [
    path('', views.index, name='random'),
    path('add_favorite', views.add_to_liste, name='add_favorite'),
    path('user/<str:username>', views.manage_account, name='account'),
    path('user/liste/<str:username>', views.manage_list, name='liste'),
]

registration/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'registration'
urlpatterns = [
    path('register', views.register, name='register'),
    path('', include("django.contrib.auth.urls")),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

randwordly/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User


class Antonyme(models.Model):
    ant_reference = models.ForeignKey('Mot', models.DO_NOTHING, db_column='ant_reference', related_name='ant_reference')
    antonyme = models.ForeignKey('Mot', models.DO_NOTHING, db_column='antonyme', related_name='antonyme')

    class Meta:
        db_table = 'antonyme'


class Definition(models.Model):
    description = models.CharField(max_length=2000)
    mot = models.ForeignKey('Mot', models.DO_NOTHING)
    exemple = models.CharField(max_length=2000, blank=True, null=True)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'definition'


class ListeApprentissage(models.Model):
    utilisateur = models.ForeignKey(User, models.DO_NOTHING)
    nom = models.CharField(max_length=500)

    def __str__(self):
        return self.nom

    class Meta:
        db_table = 'liste_apprentissage'


class Mot(models.Model):
    orthographe = models.CharField(max_length=300)
    nature_grammaticale = models.CharField(max_length=255)
    genre = models.CharField(max_length=10, blank=True, null=True)
    etymologie = models.CharField(max_length=5000)

    def __str__(self):
        return self.orthographe

    class Meta:
        db_table = 'mot'


class MotListe(models.Model):
    mot = models.ForeignKey(Mot, models.DO_NOTHING)
    liste = models.ForeignKey(ListeApprentissage, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'mot_liste'

class Note(models.Model):
    utilisateur = models.ForeignKey(User, models.DO_NOTHING)
    mot = models.ForeignKey(Mot, models.DO_NOTHING)
    note = models.CharField(max_length=2000, blank=True, null=True)

    class Meta:
        db_table = 'note'


class Reponse(models.Model):
    utilisateur = models.ForeignKey(User, models.DO_NOTHING)
    definition = models.ForeignKey(Definition, models.DO_NOTHING)
    reponse = models.IntegerField()
    date = models.DateTimeField()
    taux_validation = models.IntegerField()

    class Meta:
        db_table = 'reponse'


class Synonyme(models.Model):
    syn_reference = models.ForeignKey(Mot, models.DO_NOTHING, db_column='syn_reference', related_name='syn_reference')
    syonyme = models.ForeignKey(Mot, models.DO_NOTHING, db_column='syonyme', related_name='synonyme')

    class Meta:
        db_table = 'synonyme'


class TermeDefinition(models.Model):
    definition = models.ForeignKey(Definition, models.DO_NOTHING)
    terme = models.ForeignKey('UniteTerminologique', models.DO_NOTHING)

    class Meta:
        db_table = 'terme_definition'


class UniteTerminologique(models.Model):
    nom = models.CharField(max_length=255)
    description = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        db_table = 'unite_terminologique'

randwordly/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

randwordly/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import Mot, Definition, ListeApprentissage, MotListe
from django.contrib.auth.models import User
from django.urls import reverse

import random
import json

@csrf_exempt
def index(request):
    context = {}
    number_checked = []
    definitions = []
    random_definitions = []
    listes = []

    word_id = random.randint(1, 9000)
    number_checked.append(word_id)
    word = Mot.objects.filter(pk=word_id).first()
    context["word"] = word
    definition = str(Definition.objects.filter(mot=word_id).first()).capitalize()
    definitions.append({"description" : definition, "right_answer" : True})
    #Right definition

    if request.user.is_authenticated:
        user_liste = set([l.nom for l in ListeApprentissage.objects.filter(utilisateur=request.user.id)])
        if "random" not in user_liste:
            random_liste_creation = ListeApprentissage(utilisateur=request.user, nom="random")
            random_liste_creation.save()
            user_liste = set([l.nom for l in ListeApprentissage.objects.filter(utilisateur=request.user.id)])
        context["listes"] = list(user_liste)

    while len(number_checked) < 4 and word_id in number_checked:
        word_id = random.randint(1, 9000)
        if word_id not in number_checked:
            definition = Definition.objects.filter(mot=word_id).first()
            definitions.append({"description" :  str(definition).capitalize()})
            number_checked.append(word_id)

    for turn in range(len(definitions)):
        choice_id = random.choice(list(enumerate(definitions)))[0]
        random_definitions.append(definitions.pop(choice_id))

    context["definitions"] = random_definitions

    if request.method == 'POST':
        context["word"] = str(word)
        return JsonResponse(context)

    return render(request, 'randwordly/main.html', context)

@csrf_exempt
def add_to_liste(request):
    word = Mot.objects.filter(id=request.POST.get("word_id"))
    list_exist = ListeApprentissage.objects.filter(utilisateur=request.user, nom=request.POST.get("listes"))
    if not word or not list_exist:
        return HttpResponse(status=400)

    liste = ListeApprentissage.objects.get(nom=request.POST.get("listes"))
    MotListe.objects.create(
            liste_id=liste.id,
            mot_id=word.first().id
            ).save()
    return HttpResponse(status=200)

@login_required
def manage_account(request, username):
    return render(request, 'randwordly/account.html')

@csrf_exempt
@login_required
def manage_list(request, username):
    root = User.objects.get(id=1)
    user_listes = listes = [liste["nom"] for liste in ListeApprentissage.objects.filter(utilisateur=request.user).values('nom').distinct()]
    listes = [liste["nom"] for liste in ListeApprentissage.objects.filter(utilisateur=root).values('nom').distinct()]
    context = {"listes":sorted(listes), "user_listes":user_listes}
    if request.POST:
        alreay_exist = ListeApprentissage.objects.filter(nom=request.POST.get("new_list_name"))
        if alreay_exist:
            context["post_response"] = "liste existe déjà"
            return render(request, 'randwordly/liste.html', context)

        ListeApprentissage.objects.create(
                    utilisateur = request.user,
                    nom = request.POST.get("new_list_name"),
                    ).save()
        for liste in request.POST.getlist("list_chosen"):
            new_liste = ListeApprentissage.objects.get(nom=request.POST.get("new_list_name"))
            liste = ListeApprentissage.objects.get(nom=liste)
            words_in_liste = MotListe.objects.filter(liste_id=liste.id)
            for word in words_in_liste:
                MotListe.objects.create(
                    mot_id = word.mot_id,
                    liste_id = new_liste.id,
                    ).save()
        context["post_response"] = "liste ajoutée"
        context["user_listes"] = [liste["nom"] for liste in ListeApprentissage.objects.filter(utilisateur=request.user).values('nom').distinct()]
        return render(request, 'randwordly/liste.html', context)

    else:
        return render(request, 'randwordly/liste.html', context)

randwordly/templates/randwordly/account.html
{% extends 'randwordly/main.html' %}
{% block content %}
<a href="{% url 'randwordly:liste' user %}"> Modifier / créer une liste</a>
{% endblock %}

randwordly/templates/randwordly/liste.html
{% extends 'randwordly/main.html' %}
{% load static %}

{% block css %}
	 <link rel="stylesheet" type="text/css" href="{% static 'randwordly/liste.css' %}">
{% endblock css %}

{% block content %}
	{% if post_response %}
		<p>{{post_response}}</p>
	{% endif %}
	<section class="liste_manager">
		<form action="{% url 'randwordly:liste' user.username%}" class="creation" method="post">
			<p>Création lsite de travail</p>
			<label>Choisi des liste de référence: </label>
			<select name="list_chosen" id="list_chosen" multiple required>
				{% for liste in listes %}
					<option value="{{liste}}" name="list_chosen">{{liste}}</option>
				{% endfor %}
			</select>
			<label>Choisi un nom <abbr title="Entre 4 et 15 caractères">*</abbr></label>
			<input type="" name="new_list_name" minlength="4" maxlength="15" required>
			<input type="submit" value="Créer">
		</form>

		<div class="manage">
			<label>Choisi une liste à modifier</label>
				<select name="cars" id="cars" multiple>
				{% for liste in user_listes %}
					<option value={{liste}}>{{liste}}</option>
				{% endfor %}
			</select>
			<div class="choice">
				<button> Modifier </button>
				<button> Supprimer </button>			
			</div>
		</div>
	</section>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

randwordly/templates/randwordly/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap" rel="stylesheet"> 
	<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'randwordly/main.css' %}">
	{% block  css %} 
		
	{% endblock %}
	<title></title>
</head>
<body>
<div class="wrapper">
  <div class="box a">
  	<p>Docio</p> 
  </div>
  <nav>
  	<div>Compte</div>
  	<div><a href="{% url 'randwordly:random' %}"> Random </a></div>
  	{% if not user.is_authenticated %}
  		<div><a href="{% url 'registration:register' %}"> Inscription </a></div>
  		<div><a href="{% url 'registration:login' %}"> Connexion </a></div>
  	{% else %}
  		<div><a href="{% url 'randwordly:account' user %}"> {{user}} </a></div>
		<div><a href="{% url 'registration:logout' %}"> Deconnexion </a></div>
  	{% endif %}
  </nav>
  {% block content %}
	  <div class="guess">
	  	{% if user.is_authenticated %}
		  	<div id="liste">
			  	<label style="font-size: 2em;">Liste: </label>
			  	<select class="liste">
			  	{% for liste in listes %}
					<option value={{liste}}>{{liste}}</option>	
			  	{% endfor %}
			  	</select>
		  	</div>
		{% endif %}
	  	<div id="word_row">
	  		<h1 class="word" id={{word.id}}>{{word}}</h1>
	  		{% if user.is_authenticated %}
				<i class="material-icons fav" style="font-size:36px">star_border</i>
			{% endif %}
		</div>	
	  	<section id="definition">
	  		<div class="arrow left">
				<img hidden src="{% static 'randwordly/arrow.png' %}">
	  		</div>
		  	<div id="answers">
		  		{% for definition in definitions %}
		  			{% if "right_answer" in definition %}
		  				<button class="answer" id="True">{{definition.description}}</button>
		  			{% else %}
		  				<button class="answer">{{definition.description}}</button>
		  			{% endif %}
		  		{% endfor %}
		  	</div>
		  	<div class="arrow right">
				<img hidden src="{% static 'randwordly/arrow.png' %}">
		  	</div>
	  	</section>
	  </div>
  {% endblock content %}
  <div class="box e">E</div>
</div>
{% block javascript %}
	<script src="{% static 'randwordly/main.js' %}"></script>
{% endblock javascript %}
</body>
</html>